language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

install:
  - npm install yarn -g
  - yarn add codecov
  - yarn

script:
  - yarn run build
  - yarn run coverage -- --reporter=text-lcov > coverage.lcov
  - npx codecov -f .nyc_output/*.json

