language: node_js

os:
  - linux
  # - windows
  - osx

cache:
  timeout: 60
  npm: true
  yarn: true
  directories:
    - node_modules/ # npm packages
    - .nyc_output/

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

services:
  - redis-server

before_install:
  - npm install yarn -g
  - npm install codecov -g

install:
  - yarn install --ignore-engines

script:
  - npm run build
  - npm run coverage

after_script:
  - codecov -f .nyc_output/*.json
