language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

install:
  - npm install yarn -g
  - npm install codecov -g
  - yarn --ignore-engines

script:
  - npm run build
  - npm run coverage -- --reporter=text-lcov > coverage.lcov
  - codecov -f .nyc_output/*.json

