language: node_js

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'

install:
  - lerna bootstrap
  - npm run build

script:
  - npm install snyk
  - npm install nyc -g
  - npm test
  - npm run coverage
