language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

install:
  - npm install yarn -g
  - yarn add codecov -W
  - yarn

script:
  - npm run build
  - npm run coverage
  - npx codecov -f .nyc_output/*.json

