language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

before_install:
  - npm install yarn -g
  - yarn add codecov

install:
  - yarn

script:
  - npm run build
  - npm run coverage

after_script:
  - codecov -f .nyc_output/*.json
  - travis_terminate 0 # try to make Windows quit
