language: node_js

os:
  - windows

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'

before_install:
  - npm install yarn -g
  - npm install codecov -g

install:
  - yarn

script:
  - npm run build
  - npm run coverage

after_script:
  - travis_terminate 0 # try to make Windows quit
