language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'

install:
  - npm install codecov -g
  - npm install
  - npx lerna bootstrap
  - npm install snyk -g

script:
  - npm run build
  - npm run coverage -- --reporter=text-lcov > coverage.lcov
  - codecov

