language: node_js

os:
  - linux
  - windows
  - osx

node_js:
  - 'node'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'

install:
  - npm install lerna -g
  - lerna bootstrap
  - npm run build

script:
  - npm install snyk
  - npm run coverage:report
