export const NEST_PDD_MODULE_OPTIONS = 'NEST_PDD_MODULE_OPTIONS';
export const NEST_PDD_MODULE_PDD_CLIENTS = 'NEST_PDD_MODULE_PDD_CLIENTS';
export const NEST_PDD_MODULE_PDD_CLIENTS_ALL = Symbol('NEST_PDD_MODULE_PDD_CLIENTS_ALL');
export const NEST_PDD_MODULE_PDD_CLIENTS_DEFAULT = Symbol('NEST_PDD_MODULE_PDD_CLIENTS_DEFAULT');
