/**
 * 模块配置信息常量
 */
export const NEST_PDD_MODULE_OPTIONS = 'NEST_PDD_MODULE_OPTIONS';
/**
 * 获取所有客户端常量
 */
export const NEST_PDD_MODULE_PDD_CLIENTS_ALL = Symbol('NEST_PDD_MODULE_PDD_CLIENTS_ALL');
/**
 * 默认客户端
 */
export const NEST_PDD_MODULE_PDD_CLIENTS_DEFAULT = 'NEST_PDD_MODULE_PDD_CLIENTS_DEFAULT';
